### ISSUE TITLE
打开这个插件后，思源笔记的快捷键菜单会变成一片空白

### ISSUE THREAD

**Issue by EdwardOwl** [zuoez02/siyuan-plugin-devtool#1]
siyuan版本：2.10.6

1.打开了大量插件+devtool插件
2.关闭其他插件，只打开devtool插件
3.卸载其他插件，只保留并打开devtool插件

以上三种情况，均会出现siyuan快捷键菜单一片空白的情况

**Comment by zuoez02** [comment]
fixed
